In [22]:
import pandas as pd

In [23]:
all_seet = pd.read_excel('Other Data.xlsx', sheet_name=None)

In [24]:
Food_Detail = all_seet['Food_Details']
customer_Detail = all_seet['Customer Details']
Resturant_Detail = all_seet['Resturant_Details']

In [25]:
# Food_Detail ........................................................................................................

In [26]:
Food_Detail.head()

   ItemCode       Food Name    Food_Type
0      2142  Butter Chicken  Main Course
1      2152    Palak Paneer  Main Course
2      2145   Chole Bhature  Main Course
3      2149         Biryani  Main Course
4      2141     Masala Dosa    Breakfast

In [27]:
Food_Detail.shape

(23, 3)

In [28]:
Food_Detail.isnull().sum()

ItemCode     0
Food Name    0
Food_Type    0
dtype: int64

In [29]:
Food_Detail.duplicated().sum()

np.int64(0)

In [30]:
# customer_Detail.......................................................................................

In [31]:
customer_Detail.head()

   customer_id  customer_name member_Type
0            1      Sai Naidu        Gold
1            2  Krishna Menon           G
2            3     Uday Menon        Gold
3            4   Kartik Patel        Gold
4            5   Shaurya Jain     Regular

In [32]:
customer_Detail.shape

(30, 3)

In [33]:
customer_Detail.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    30 non-null     int64
 1   customer_name  30 non-null     str
 2   member_Type    30 non-null     str
dtypes: int64(1), str(2)
memory usage: 852.0 bytes

In [34]:
customer_Detail.isnull().sum()

customer_id      0
customer_name    0
member_Type      0
dtype: int64

In [35]:
customer_Detail.duplicated().sum()

np.int64(0)

In [40]:
customer_Detail.columns

Index(['customer_id', 'customer_name', 'member_Type'], dtype='str')

In [42]:
customer_Detail['member_Type'].unique()

<StringArray>
['Gold', 'G', 'Regular', 'R']
Length: 4, dtype: str

In [44]:
customer_Detail['member_Type'] = customer_Detail['member_Type'].replace({
    'G':'Gold', 
    'R':'Regular'
})

In [45]:
customer_Detail['member_Type'].unique()

<StringArray>
['Gold', 'Regular']
Length: 2, dtype: str

In [46]:
customer_Detail

    customer_id     customer_name member_Type
0             1         Sai Naidu        Gold
1             2     Krishna Menon        Gold
2             3        Uday Menon        Gold
3             4      Kartik Patel        Gold
4             5      Shaurya Jain     Regular
5             6       Shyam Yadav        Gold
6             7       Aditya Iyer     Regular
7             8     Reyansh Yadav        Gold
8             9       Ashok Naidu     Regular
9            10        Parth Jain        Gold
10           11      Arjun Mishra     Regular
11           12       Aniket Shah     Regular
12           13  Dinesh Choudhary     Regular
13           14      Ishaan Desai     Regular
14           15   Keshav Malhotra     Regular
15           16     Vivaan Kapoor        Gold
16           17     Chetan Bhatia        Gold
17           18        Arnav Iyer        Gold
18           19       Aarav Gupta        Gold
19           20   Atharv Malhotra        Gold
20           21       Vihaan Shah        Gold
21           22   Ayaan Choudhary        Gold
22           23       Manoj Gupta        Gold
23           24       Alok Kapoor        Gold
24           25     Rituraj Desai     Regular
25           26    Subhash Mishra        Gold
26           27      Rohit Kapoor        Gold
27           28      Vikram Joshi        Gold
28           29        Bharat Rao        Gold
29           30       Rakesh Nair     Regular

In [47]:
Resturant_Detail.head()

   Resturant_Code   Resturant_Name Resturant_type
0             212          Bukhara   North Indian
1             213        Karavalli        Mughlai
2             211  Saravana Bhavan   North Indian
3             216       Moti Mahal        Mughlai
4             217          Dakshin   South Indian

In [48]:
Resturant_Detail.shape

(6, 3)